MAX_NAME_LENGTH: 50
MAX_EMAIL_LENGTH: 255
MIN_PASSWORD_LENGTH: 6
BOOK_PER_PAGE: 10
OBJECT_PER_PAGE: 10
EXPIRED_YEAR: 2
EXPIRED_HOUR: 2
EXPIRED_WEEK: 2
MAX_BORROWED_BOOK: 5
NOTIFICATION_PER_PAGE: 10
LIBRARIAN_ID: 2
ADMIN_ID: 1

SIZE_IMAGE_OPTION: 80
SIZE_IMAGE_OPTION_SMALL: 50
MAX_SIZE_PICTURE_MB: 5
LIMIT_SIZE_PICTURE: 400

IMAGE_FORMAT: "image/jpeg,image/gif,image/png"
