MAX_NAME_LENGTH: 50
MAX_EMAIL_LENGTH: 255
MIN_PASSWORD_LENGTH: 6
BOOK_PER_PAGE: 6
OBJECT_PER_PAGE: 6
EXPIRED_YEAR: 2
EXPIRED_HOUR: 2
EXPIRED_WEEK: 2
MAX_BORROWED_BOOK: 5
NOTIFICATION_PER_PAGE: 10
LIBRARIAN_ID: 2
ADMIN_ID: 1

SIZE_IMAGE_OPTION: 80
SIZE_IMAGE_OPTION_SMALL: 50
MAX_SIZE_PICTURE_MB: 5
LIMIT_SIZE_PICTURE: 400
SIZE_TERMS_SERVICE: "115x15"

IMAGE_FORMAT: "image/jpeg,image/gif,image/png"
IMAGE_LOGO: "http://res.cloudinary.com/hoangnguyen679/image/upload/v1533283233/logo.png"
IMAGE_ACCESS: "https://res.cloudinary.com/hoangnguyen679/image/upload/v1533283398/access.jpg"
IMAGE_BOOK: "https://res.cloudinary.com/hoangnguyen679/image/upload/v1533283581/book-wallpaper.jpg"
IMAGE_HOME: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534644953/glyphicons-home.png"
IMAGE_BOOK_ICON: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534645954/glyphicons-book.png"
IMAGE_LANGUAGE: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534646393/translation.png"
IMAGE_LOGIN: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534647796/glyphicons-log-in.png"
IMAGE_VI: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534648824/vietnam.png"
IMAGE_EN: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534648829/england.png"
IMAGE_JA: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534648836/japan.png"
IMAGE_USER: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534652777/group-user.png"
IMAGE_ACCOUNT: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534652949/drop-down.png"
IMAGE_SEARCH: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534654400/search.png"
IMAGE_ADVANCE: "https://res.cloudinary.com/dmra0gt0z/image/upload/v1534654917/advance.png"
